use bevy::{
    input::{
        keyboard::{KeyCode, KeyboardInput},
        mouse::MouseButton,
        touch::{ForceTouch, TouchInput, TouchPhase},
        ButtonState,
    },
    math::Vec2,
    window::CursorIcon,
};
use wry::application as tao;

pub fn convert_keyboard_input(key_event: &tao::event::KeyEvent) -> KeyboardInput {
    KeyboardInput {
        scan_code: convert_physical_key(key_event.physical_key),
        state: convert_element_state(key_event.state),
        key_code: convert_logical_key(&key_event.logical_key),
    }
}

pub fn convert_element_state(element_state: tao::event::ElementState) -> ButtonState {
    match element_state {
        tao::event::ElementState::Pressed => ButtonState::Pressed,
        tao::event::ElementState::Released => ButtonState::Released,
        _ => unreachable!(),
    }
}

pub fn convert_mouse_button(mouse_button: tao::event::MouseButton) -> MouseButton {
    match mouse_button {
        tao::event::MouseButton::Left => MouseButton::Left,
        tao::event::MouseButton::Right => MouseButton::Right,
        tao::event::MouseButton::Middle => MouseButton::Middle,
        tao::event::MouseButton::Other(val) => MouseButton::Other(val),
        _ => unreachable!(),
    }
}

pub fn convert_touch_input(
    touch_input: tao::event::Touch,
    location: tao::dpi::LogicalPosition<f64>,
) -> TouchInput {
    TouchInput {
        phase: match touch_input.phase {
            tao::event::TouchPhase::Started => TouchPhase::Started,
            tao::event::TouchPhase::Moved => TouchPhase::Moved,
            tao::event::TouchPhase::Ended => TouchPhase::Ended,
            tao::event::TouchPhase::Cancelled => TouchPhase::Cancelled,
            _ => unreachable!(),
        },
        position: Vec2::new(location.x as f32, location.y as f32),
        force: touch_input.force.map(|f| match f {
            tao::event::Force::Calibrated {
                force,
                max_possible_force,
                altitude_angle,
                ..
            } => ForceTouch::Calibrated {
                force,
                max_possible_force,
                altitude_angle,
            },
            tao::event::Force::Normalized(x) => ForceTouch::Normalized(x),
            _ => unreachable!(),
        }),
        id: touch_input.id,
    }
}

fn convert_physical_key(_logical_key: tao::keyboard::KeyCode) -> u32 {
    todo!();
}

fn convert_logical_key(_logical_key: &tao::keyboard::Key<'static>) -> Option<KeyCode> {
    todo!();
}

// pub fn convert_virtual_key_code(virtual_key_code: tao::event::VirtualKeyCode) -> KeyCode {
//     match virtual_key_code {
//         tao::event::VirtualKeyCode::Key1 => KeyCode::Key1,
//         tao::event::VirtualKeyCode::Key2 => KeyCode::Key2,
//         tao::event::VirtualKeyCode::Key3 => KeyCode::Key3,
//         tao::event::VirtualKeyCode::Key4 => KeyCode::Key4,
//         tao::event::VirtualKeyCode::Key5 => KeyCode::Key5,
//         tao::event::VirtualKeyCode::Key6 => KeyCode::Key6,
//         tao::event::VirtualKeyCode::Key7 => KeyCode::Key7,
//         tao::event::VirtualKeyCode::Key8 => KeyCode::Key8,
//         tao::event::VirtualKeyCode::Key9 => KeyCode::Key9,
//         tao::event::VirtualKeyCode::Key0 => KeyCode::Key0,
//         tao::event::VirtualKeyCode::A => KeyCode::A,
//         tao::event::VirtualKeyCode::B => KeyCode::B,
//         tao::event::VirtualKeyCode::C => KeyCode::C,
//         tao::event::VirtualKeyCode::D => KeyCode::D,
//         tao::event::VirtualKeyCode::E => KeyCode::E,
//         tao::event::VirtualKeyCode::F => KeyCode::F,
//         tao::event::VirtualKeyCode::G => KeyCode::G,
//         tao::event::VirtualKeyCode::H => KeyCode::H,
//         tao::event::VirtualKeyCode::I => KeyCode::I,
//         tao::event::VirtualKeyCode::J => KeyCode::J,
//         tao::event::VirtualKeyCode::K => KeyCode::K,
//         tao::event::VirtualKeyCode::L => KeyCode::L,
//         tao::event::VirtualKeyCode::M => KeyCode::M,
//         tao::event::VirtualKeyCode::N => KeyCode::N,
//         tao::event::VirtualKeyCode::O => KeyCode::O,
//         tao::event::VirtualKeyCode::P => KeyCode::P,
//         tao::event::VirtualKeyCode::Q => KeyCode::Q,
//         tao::event::VirtualKeyCode::R => KeyCode::R,
//         tao::event::VirtualKeyCode::S => KeyCode::S,
//         tao::event::VirtualKeyCode::T => KeyCode::T,
//         tao::event::VirtualKeyCode::U => KeyCode::U,
//         tao::event::VirtualKeyCode::V => KeyCode::V,
//         tao::event::VirtualKeyCode::W => KeyCode::W,
//         tao::event::VirtualKeyCode::X => KeyCode::X,
//         tao::event::VirtualKeyCode::Y => KeyCode::Y,
//         tao::event::VirtualKeyCode::Z => KeyCode::Z,
//         tao::event::VirtualKeyCode::Escape => KeyCode::Escape,
//         tao::event::VirtualKeyCode::F1 => KeyCode::F1,
//         tao::event::VirtualKeyCode::F2 => KeyCode::F2,
//         tao::event::VirtualKeyCode::F3 => KeyCode::F3,
//         tao::event::VirtualKeyCode::F4 => KeyCode::F4,
//         tao::event::VirtualKeyCode::F5 => KeyCode::F5,
//         tao::event::VirtualKeyCode::F6 => KeyCode::F6,
//         tao::event::VirtualKeyCode::F7 => KeyCode::F7,
//         tao::event::VirtualKeyCode::F8 => KeyCode::F8,
//         tao::event::VirtualKeyCode::F9 => KeyCode::F9,
//         tao::event::VirtualKeyCode::F10 => KeyCode::F10,
//         tao::event::VirtualKeyCode::F11 => KeyCode::F11,
//         tao::event::VirtualKeyCode::F12 => KeyCode::F12,
//         tao::event::VirtualKeyCode::F13 => KeyCode::F13,
//         tao::event::VirtualKeyCode::F14 => KeyCode::F14,
//         tao::event::VirtualKeyCode::F15 => KeyCode::F15,
//         tao::event::VirtualKeyCode::F16 => KeyCode::F16,
//         tao::event::VirtualKeyCode::F17 => KeyCode::F17,
//         tao::event::VirtualKeyCode::F18 => KeyCode::F18,
//         tao::event::VirtualKeyCode::F19 => KeyCode::F19,
//         tao::event::VirtualKeyCode::F20 => KeyCode::F20,
//         tao::event::VirtualKeyCode::F21 => KeyCode::F21,
//         tao::event::VirtualKeyCode::F22 => KeyCode::F22,
//         tao::event::VirtualKeyCode::F23 => KeyCode::F23,
//         tao::event::VirtualKeyCode::F24 => KeyCode::F24,
//         tao::event::VirtualKeyCode::Snapshot => KeyCode::Snapshot,
//         tao::event::VirtualKeyCode::Scroll => KeyCode::Scroll,
//         tao::event::VirtualKeyCode::Pause => KeyCode::Pause,
//         tao::event::VirtualKeyCode::Insert => KeyCode::Insert,
//         tao::event::VirtualKeyCode::Home => KeyCode::Home,
//         tao::event::VirtualKeyCode::Delete => KeyCode::Delete,
//         tao::event::VirtualKeyCode::End => KeyCode::End,
//         tao::event::VirtualKeyCode::PageDown => KeyCode::PageDown,
//         tao::event::VirtualKeyCode::PageUp => KeyCode::PageUp,
//         tao::event::VirtualKeyCode::Left => KeyCode::Left,
//         tao::event::VirtualKeyCode::Up => KeyCode::Up,
//         tao::event::VirtualKeyCode::Right => KeyCode::Right,
//         tao::event::VirtualKeyCode::Down => KeyCode::Down,
//         tao::event::VirtualKeyCode::Back => KeyCode::Back,
//         tao::event::VirtualKeyCode::Return => KeyCode::Return,
//         tao::event::VirtualKeyCode::Space => KeyCode::Space,
//         tao::event::VirtualKeyCode::Compose => KeyCode::Compose,
//         tao::event::VirtualKeyCode::Caret => KeyCode::Caret,
//         tao::event::VirtualKeyCode::Numlock => KeyCode::Numlock,
//         tao::event::VirtualKeyCode::Numpad0 => KeyCode::Numpad0,
//         tao::event::VirtualKeyCode::Numpad1 => KeyCode::Numpad1,
//         tao::event::VirtualKeyCode::Numpad2 => KeyCode::Numpad2,
//         tao::event::VirtualKeyCode::Numpad3 => KeyCode::Numpad3,
//         tao::event::VirtualKeyCode::Numpad4 => KeyCode::Numpad4,
//         tao::event::VirtualKeyCode::Numpad5 => KeyCode::Numpad5,
//         tao::event::VirtualKeyCode::Numpad6 => KeyCode::Numpad6,
//         tao::event::VirtualKeyCode::Numpad7 => KeyCode::Numpad7,
//         tao::event::VirtualKeyCode::Numpad8 => KeyCode::Numpad8,
//         tao::event::VirtualKeyCode::Numpad9 => KeyCode::Numpad9,
//         tao::event::VirtualKeyCode::AbntC1 => KeyCode::AbntC1,
//         tao::event::VirtualKeyCode::AbntC2 => KeyCode::AbntC2,
//         tao::event::VirtualKeyCode::NumpadAdd => KeyCode::NumpadAdd,
//         tao::event::VirtualKeyCode::Apostrophe => KeyCode::Apostrophe,
//         tao::event::VirtualKeyCode::Apps => KeyCode::Apps,
//         tao::event::VirtualKeyCode::Asterisk => KeyCode::Asterisk,
//         tao::event::VirtualKeyCode::Plus => KeyCode::Plus,
//         tao::event::VirtualKeyCode::At => KeyCode::At,
//         tao::event::VirtualKeyCode::Ax => KeyCode::Ax,
//         tao::event::VirtualKeyCode::Backslash => KeyCode::Backslash,
//         tao::event::VirtualKeyCode::Calculator => KeyCode::Calculator,
//         tao::event::VirtualKeyCode::Capital => KeyCode::Capital,
//         tao::event::VirtualKeyCode::Colon => KeyCode::Colon,
//         tao::event::VirtualKeyCode::Comma => KeyCode::Comma,
//         tao::event::VirtualKeyCode::Convert => KeyCode::Convert,
//         tao::event::VirtualKeyCode::NumpadDecimal => KeyCode::NumpadDecimal,
//         tao::event::VirtualKeyCode::NumpadDivide => KeyCode::NumpadDivide,
//         tao::event::VirtualKeyCode::Equals => KeyCode::Equals,
//         tao::event::VirtualKeyCode::Grave => KeyCode::Grave,
//         tao::event::VirtualKeyCode::Kana => KeyCode::Kana,
//         tao::event::VirtualKeyCode::Kanji => KeyCode::Kanji,
//         tao::event::VirtualKeyCode::LAlt => KeyCode::LAlt,
//         tao::event::VirtualKeyCode::LBracket => KeyCode::LBracket,
//         tao::event::VirtualKeyCode::LControl => KeyCode::LControl,
//         tao::event::VirtualKeyCode::LShift => KeyCode::LShift,
//         tao::event::VirtualKeyCode::LWin => KeyCode::LWin,
//         tao::event::VirtualKeyCode::Mail => KeyCode::Mail,
//         tao::event::VirtualKeyCode::MediaSelect => KeyCode::MediaSelect,
//         tao::event::VirtualKeyCode::MediaStop => KeyCode::MediaStop,
//         tao::event::VirtualKeyCode::Minus => KeyCode::Minus,
//         tao::event::VirtualKeyCode::NumpadMultiply => KeyCode::NumpadMultiply,
//         tao::event::VirtualKeyCode::Mute => KeyCode::Mute,
//         tao::event::VirtualKeyCode::MyComputer => KeyCode::MyComputer,
//         tao::event::VirtualKeyCode::NavigateForward => KeyCode::NavigateForward,
//         tao::event::VirtualKeyCode::NavigateBackward => KeyCode::NavigateBackward,
//         tao::event::VirtualKeyCode::NextTrack => KeyCode::NextTrack,
//         tao::event::VirtualKeyCode::NoConvert => KeyCode::NoConvert,
//         tao::event::VirtualKeyCode::NumpadComma => KeyCode::NumpadComma,
//         tao::event::VirtualKeyCode::NumpadEnter => KeyCode::NumpadEnter,
//         tao::event::VirtualKeyCode::NumpadEquals => KeyCode::NumpadEquals,
//         tao::event::VirtualKeyCode::OEM102 => KeyCode::Oem102,
//         tao::event::VirtualKeyCode::Period => KeyCode::Period,
//         tao::event::VirtualKeyCode::PlayPause => KeyCode::PlayPause,
//         tao::event::VirtualKeyCode::Power => KeyCode::Power,
//         tao::event::VirtualKeyCode::PrevTrack => KeyCode::PrevTrack,
//         tao::event::VirtualKeyCode::RAlt => KeyCode::RAlt,
//         tao::event::VirtualKeyCode::RBracket => KeyCode::RBracket,
//         tao::event::VirtualKeyCode::RControl => KeyCode::RControl,
//         tao::event::VirtualKeyCode::RShift => KeyCode::RShift,
//         tao::event::VirtualKeyCode::RWin => KeyCode::RWin,
//         tao::event::VirtualKeyCode::Semicolon => KeyCode::Semicolon,
//         tao::event::VirtualKeyCode::Slash => KeyCode::Slash,
//         tao::event::VirtualKeyCode::Sleep => KeyCode::Sleep,
//         tao::event::VirtualKeyCode::Stop => KeyCode::Stop,
//         tao::event::VirtualKeyCode::NumpadSubtract => KeyCode::NumpadSubtract,
//         tao::event::VirtualKeyCode::Sysrq => KeyCode::Sysrq,
//         tao::event::VirtualKeyCode::Tab => KeyCode::Tab,
//         tao::event::VirtualKeyCode::Underline => KeyCode::Underline,
//         tao::event::VirtualKeyCode::Unlabeled => KeyCode::Unlabeled,
//         tao::event::VirtualKeyCode::VolumeDown => KeyCode::VolumeDown,
//         tao::event::VirtualKeyCode::VolumeUp => KeyCode::VolumeUp,
//         tao::event::VirtualKeyCode::Wake => KeyCode::Wake,
//         tao::event::VirtualKeyCode::WebBack => KeyCode::WebBack,
//         tao::event::VirtualKeyCode::WebFavorites => KeyCode::WebFavorites,
//         tao::event::VirtualKeyCode::WebForward => KeyCode::WebForward,
//         tao::event::VirtualKeyCode::WebHome => KeyCode::WebHome,
//         tao::event::VirtualKeyCode::WebRefresh => KeyCode::WebRefresh,
//         tao::event::VirtualKeyCode::WebSearch => KeyCode::WebSearch,
//         tao::event::VirtualKeyCode::WebStop => KeyCode::WebStop,
//         tao::event::VirtualKeyCode::Yen => KeyCode::Yen,
//         tao::event::VirtualKeyCode::Copy => KeyCode::Copy,
//         tao::event::VirtualKeyCode::Paste => KeyCode::Paste,
//         tao::event::VirtualKeyCode::Cut => KeyCode::Cut,
//     }
// }

pub fn convert_cursor_icon(cursor_icon: CursorIcon) -> tao::window::CursorIcon {
    match cursor_icon {
        CursorIcon::Default => tao::window::CursorIcon::Default,
        CursorIcon::Crosshair => tao::window::CursorIcon::Crosshair,
        CursorIcon::Hand => tao::window::CursorIcon::Hand,
        CursorIcon::Arrow => tao::window::CursorIcon::Arrow,
        CursorIcon::Move => tao::window::CursorIcon::Move,
        CursorIcon::Text => tao::window::CursorIcon::Text,
        CursorIcon::Wait => tao::window::CursorIcon::Wait,
        CursorIcon::Help => tao::window::CursorIcon::Help,
        CursorIcon::Progress => tao::window::CursorIcon::Progress,
        CursorIcon::NotAllowed => tao::window::CursorIcon::NotAllowed,
        CursorIcon::ContextMenu => tao::window::CursorIcon::ContextMenu,
        CursorIcon::Cell => tao::window::CursorIcon::Cell,
        CursorIcon::VerticalText => tao::window::CursorIcon::VerticalText,
        CursorIcon::Alias => tao::window::CursorIcon::Alias,
        CursorIcon::Copy => tao::window::CursorIcon::Copy,
        CursorIcon::NoDrop => tao::window::CursorIcon::NoDrop,
        CursorIcon::Grab => tao::window::CursorIcon::Grab,
        CursorIcon::Grabbing => tao::window::CursorIcon::Grabbing,
        CursorIcon::AllScroll => tao::window::CursorIcon::AllScroll,
        CursorIcon::ZoomIn => tao::window::CursorIcon::ZoomIn,
        CursorIcon::ZoomOut => tao::window::CursorIcon::ZoomOut,
        CursorIcon::EResize => tao::window::CursorIcon::EResize,
        CursorIcon::NResize => tao::window::CursorIcon::NResize,
        CursorIcon::NeResize => tao::window::CursorIcon::NeResize,
        CursorIcon::NwResize => tao::window::CursorIcon::NwResize,
        CursorIcon::SResize => tao::window::CursorIcon::SResize,
        CursorIcon::SeResize => tao::window::CursorIcon::SeResize,
        CursorIcon::SwResize => tao::window::CursorIcon::SwResize,
        CursorIcon::WResize => tao::window::CursorIcon::WResize,
        CursorIcon::EwResize => tao::window::CursorIcon::EwResize,
        CursorIcon::NsResize => tao::window::CursorIcon::NsResize,
        CursorIcon::NeswResize => tao::window::CursorIcon::NeswResize,
        CursorIcon::NwseResize => tao::window::CursorIcon::NwseResize,
        CursorIcon::ColResize => tao::window::CursorIcon::ColResize,
        CursorIcon::RowResize => tao::window::CursorIcon::RowResize,
    }
}

// pub fn convert_window_level(window_level: WindowLevel) -> tao::window::WindowLevel {
//     match window_level {
//         WindowLevel::AlwaysOnBottom => tao::window::WindowLevel::AlwaysOnBottom,
//         WindowLevel::Normal => tao::window::WindowLevel::Normal,
//         WindowLevel::AlwaysOnTop => tao::window::WindowLevel::AlwaysOnTop,
//     }
// }
