[package]
name = "bevy_dioxus_desktop"
version = "0.1.1"
authors = ["Junichi Sugiura"]
edition = "2021"
description = "Write cross-platform application with React-like declarative UI framework and scalable ECS architecture all in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/JunichiSugiura/bevy_dioxus/"
homepage = "https://github.com/JunichiSugiura/bevy_dioxus/"
documentation = "https://docs.rs/bevy_dioxus/latest/bevy_dioxus/"
keywords = ["declarative-ui", "ecs", "bevy", "dioxus", "cross-platform"]

[dependencies]
approx = "0.5.1"
bevy = { version = "0.8", default-features = false }
bevy_dioxus_core = { version = "0.1", path = "../core"}
dioxus-core = { version = "0.2", features = ["serialize"] }
dioxus-hooks = "0.2"
dioxus-html = { version = "0.2", features = ["serialize"] }
dioxus-interpreter-js = "0.2"
dunce = "1.0"
fermi = "0.2"
futures-channel = "0.3.21"
futures-intrusive = "0.4"
log = "0.4"
mime_guess = "2.0"
raw-window-handle = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
tokio = { version = "1.18", features = ["rt-multi-thread", "macros"], default-features = false }
webbrowser = "0.5"
wry = "0.16"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[dev-dependencies]
bevy_dioxus = { version = "0.1", path = "../.." }
dioxus = "0.2"
