[package]
name = "dip_macro"
version = "0.1.0"
authors = ["Junichi Sugiura"]
edition = "2021"
description = "Write cross-platform application with React-like declarative UI framework and scalable ECS architecture all in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/diptools/dip/"
homepage = "https://github.com/diptools/dip/"
documentation = "https://docs.rs/dip/latest/dip/"
keywords = ["declarative-ui", "ecs", "bevy", "dioxus", "cross-platform"]

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5"
fermi = "0.2"
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = [ "full", "fold" ]}
