[package]
name = "dip_cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true

[dependencies]
bevy = { version = "0.8", default-features = false }

dip_macro = { version = "0.1", path = "../macro" }
